version: '3.8'
name: 'dictionary'

services:
  database:
    image: postgres:latest
    container_name: dictionary-database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: back_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dictionary-database:/var/lib/postgresql/data

volumes:
  dictionary-database:
    name: dictionary-database
